#!/usr/bin/env bash
# Populate sage-desktop/offline/wheels/ with every wheel needed to install
# the SAGE sidecar deps offline. Used for air-gapped dev machines and for
# producing an "offline installer" tarball alongside the signed MSI.
#
# Output: sage-desktop/offline/wheels/*.whl
#         sage-desktop/offline/MANIFEST.txt (sha256 of each wheel)
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
desktop_dir="$(cd "${script_dir}/.." && pwd)"
repo_root="$(cd "${desktop_dir}/.." && pwd)"
wheels_dir="${desktop_dir}/offline/wheels"
manifest="${desktop_dir}/offline/MANIFEST.txt"

if [[ -x "${repo_root}/.venv/Scripts/python.exe" ]]; then
    py="${repo_root}/.venv/Scripts/python.exe"
elif [[ -x "${repo_root}/.venv/bin/python" ]]; then
    py="${repo_root}/.venv/bin/python"
else
    echo "ERROR: no .venv found at ${repo_root}/.venv — run 'make venv' first" >&2
    exit 1
fi

mkdir -p "${wheels_dir}"
rm -f "${wheels_dir}"/*.whl "${wheels_dir}"/*.tar.gz 2>/dev/null || true

echo "downloading wheels into ${wheels_dir}"
"${py}" -m pip download \
    --dest "${wheels_dir}" \
    --requirement "${repo_root}/requirements.txt" \
    --only-binary=:all: \
    --platform win_amd64 \
    --python-version 3.12 \
    --implementation cp \
    --abi cp312 \
    || {
        # Some deps are pure-python sdists. Retry without --only-binary and
        # accept source distributions as a fallback.
        echo "retrying with sdists allowed for pure-python packages"
        "${py}" -m pip download \
            --dest "${wheels_dir}" \
            --requirement "${repo_root}/requirements.txt"
    }

echo "writing ${manifest}"
{
    echo "# Generated by build-offline-cache.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    cd "${wheels_dir}"
    for f in *.whl *.tar.gz; do
        [[ -f "${f}" ]] || continue
        sha=$("${py}" -c "import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "${f}")
        echo "${sha}  ${f}"
    done
} > "${manifest}"

count=$(ls -1 "${wheels_dir}" | wc -l)
echo "cached ${count} package files under ${wheels_dir}"
