// Single source of truth for risk presentation — generated by SAGE's own
// Evaluator-Optimizer loop (Claude optimized, Gemini-3.5-flash evaluated to 10/10)
// and applied via the human approval gate. Replaces the risk-color maps that were
// re-declared in Approvals.tsx, proposals/ProposalCard.tsx, and Dashboard.tsx.
import React from 'react';

export type RiskLevel = 'DESTRUCTIVE' | 'EXTERNAL' | 'STATEFUL' | 'EPHEMERAL' | 'INFORMATIONAL';

interface RiskBadgeProps {
  risk: RiskLevel;
  className?: string;
}

export interface RiskConfigEntry {
  icon: string;
  title: string;
  bgVar: string;
  colorVar: string;
  borderVar: string;
}

// Exported so layout accents (status dots, borders) can use the SAME tokens
// instead of re-declaring hex — one config, every consumer.
export const RISK_CONFIG: Record<RiskLevel, RiskConfigEntry> = {
  DESTRUCTIVE: {
    icon: '⊗',
    title: 'This action permanently deletes or overwrites data and cannot be undone.',
    bgVar: 'var(--sage-risk-destructive-bg)',
    colorVar: 'var(--sage-risk-destructive-fg)',
    borderVar: 'var(--sage-risk-destructive-border)',
  },
  EXTERNAL: {
    icon: '↗',
    title: 'This action sends data or requests to an external system outside SAGE.',
    bgVar: 'var(--sage-risk-external-bg)',
    colorVar: 'var(--sage-risk-external-fg)',
    borderVar: 'var(--sage-risk-external-border)',
  },
  STATEFUL: {
    icon: '◈',
    title: 'This action modifies persistent state such as configuration, files, or database records.',
    bgVar: 'var(--sage-risk-stateful-bg)',
    colorVar: 'var(--sage-risk-stateful-fg)',
    borderVar: 'var(--sage-risk-stateful-border)',
  },
  EPHEMERAL: {
    icon: '◌',
    title: 'This action produces temporary output that will not persist after the session ends.',
    bgVar: 'var(--sage-risk-ephemeral-bg)',
    colorVar: 'var(--sage-risk-ephemeral-fg)',
    borderVar: 'var(--sage-risk-ephemeral-border)',
  },
  INFORMATIONAL: {
    icon: 'ℹ',
    title: 'This action only reads or surfaces information and makes no changes.',
    bgVar: 'var(--sage-risk-informational-bg)',
    colorVar: 'var(--sage-risk-informational-fg)',
    borderVar: 'var(--sage-risk-informational-border)',
  },
};

export const RiskBadge: React.FC<RiskBadgeProps> = ({ risk, className }) => {
  const config = RISK_CONFIG[risk];

  return (
    <span
      title={config.title}
      aria-label={`Risk level: ${risk}. ${config.title}`}
      role="img"
      className={className}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        gap: '0.3em',
        padding: '0.2em 0.55em',
        borderRadius: '0.375rem',
        border: `1px solid ${config.borderVar}`,
        backgroundColor: config.bgVar,
        color: config.colorVar,
        fontSize: '0.75rem',
        fontWeight: 600,
        letterSpacing: '0.03em',
        lineHeight: 1.4,
        userSelect: 'none',
        whiteSpace: 'nowrap',
      }}
    >
      <span aria-hidden="true" style={{ fontSize: '0.85em', lineHeight: 1 }}>
        {config.icon}
      </span>
      <span>{risk}</span>
    </span>
  );
};

export default RiskBadge;
