"""
SAGE[ai] - End-to-End tests for Monitor → Notification flow

Tests that events from Teams, Metabase, and GitLab correctly trigger
agent actions and audit log entries.
"""

import json
import sqlite3
from unittest.mock import MagicMock, patch

import pytest


pytestmark = pytest.mark.e2e

FIXED_ANALYSIS = {
    "severity": "HIGH",
    "root_cause_hypothesis": "test hypothesis",
    "recommended_action": "test action",
    "trace_id": "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee",
}

MR_DRAFT_JSON = json.dumps({
    "mr_title": "Fix: sage-ai issue",
    "mr_description": "Resolves #1\n\nAuto-generated by SAGE[ai].",
})


def _query_audit(db_path, action_type):
    conn = sqlite3.connect(db_path)
    rows = conn.execute(
        "SELECT * FROM compliance_audit_log WHERE action_type = ?", (action_type,)
    ).fetchall()
    conn.close()
    return rows


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------


def test_teams_error_triggers_analyst(tmp_audit_db):
    """
    When MonitorAgent fires a 'teams_error' event, a registered callback
    that calls analyst.analyze_log() must be invoked with the event content.
    """
    mock_analyst = MagicMock()
    mock_analyst.analyze_log.return_value = FIXED_ANALYSIS

    from src.agents.monitor import MonitorAgent
    agent = MonitorAgent()
    agent._audit_logger = tmp_audit_db

    # Register a callback that mimics what a real Teams handler would do
    def teams_error_handler(payload):
        content = payload.get("content", "")
        mock_analyst.analyze_log(content)

    agent.register_callback("teams_error", teams_error_handler)

    payload = {
        "type": "teams_error",
        "source": "teams",
        "content": "ERROR 0x55 on device COM3 — sensor read timeout",
        "from": "Alert Bot",
        "timestamp": "2024-01-15T10:00:00Z",
        "matched_keywords": ["error"],
        "message_id": "msg-001",
    }
    agent._on_event("teams_error", payload)

    assert mock_analyst.analyze_log.called, "analyst.analyze_log() must be called by the callback."
    call_arg = mock_analyst.analyze_log.call_args[0][0]
    assert "ERROR 0x55" in call_arg, f"Expected error content in analyze_log() call: {call_arg!r}"


def test_metabase_error_triggers_notification(tmp_audit_db):
    """
    When MonitorAgent fires a 'metabase_error' event, a registered callback
    that calls a Teams alert function must be invoked.
    """
    mock_teams_alert = MagicMock()
    mock_teams_alert.return_value = {"status": "sent"}

    from src.agents.monitor import MonitorAgent
    agent = MonitorAgent()
    agent._audit_logger = tmp_audit_db

    def metabase_error_handler(payload):
        content = payload.get("content", "")
        mock_teams_alert(title="Metabase Error Detected", message=content)

    agent.register_callback("metabase_error", metabase_error_handler)

    error_payload = {
        "type": "metabase_error",
        "source": "metabase",
        "content": '{"error_code": "E001", "message": "Sensor read failed 15 times in last hour"}',
        "timestamp": "2024-01-15T10:00:00Z",
        "error_data": {"error_code": "E001", "message": "Sensor read failed 15 times in last hour"},
    }
    agent._on_event("metabase_error", error_payload)

    assert mock_teams_alert.called, "Teams alert function must be called on metabase_error event."
    call_kwargs = mock_teams_alert.call_args
    assert "Metabase Error Detected" in str(call_kwargs), (
        f"Expected alert title in call: {call_kwargs}"
    )


def test_gitlab_issue_triggers_mr_creation(tmp_audit_db):
    """
    When MonitorAgent fires a 'gitlab_issue' event, a registered callback
    that calls developer.create_mr_from_issue() must be invoked.
    """
    mock_developer = MagicMock()
    mock_developer.create_mr_from_issue.return_value = {
        "mr_iid": 10,
        "mr_url": "https://gitlab.example.com/project/-/merge_requests/10",
        "trace_id": "bbbbbbbb-cccc-4ddd-8eee-ffffffffffff",
    }

    from src.agents.monitor import MonitorAgent
    agent = MonitorAgent()
    agent._audit_logger = tmp_audit_db

    def gitlab_issue_handler(payload):
        issue_iid = payload.get("issue_iid")
        project_id = 123  # Default project from config
        mock_developer.create_mr_from_issue(project_id=project_id, issue_iid=issue_iid)

    agent.register_callback("gitlab_issue", gitlab_issue_handler)

    issue_payload = {
        "type": "gitlab_issue",
        "source": "gitlab",
        "content": "Issue #1: UART buffer overflow — auto-fix required",
        "timestamp": "2024-01-15T10:00:00Z",
        "issue_iid": 1,
        "issue_id": 5001,
        "title": "UART buffer overflow — auto-fix required",
        "description": "Buffer size insufficient for high-throughput scenarios.",
        "labels": ["sage-ai", "auto-fix"],
        "web_url": "https://gitlab.example.com/project/-/issues/1",
    }
    agent._on_event("gitlab_issue", issue_payload)

    assert mock_developer.create_mr_from_issue.called, (
        "developer.create_mr_from_issue() must be called on gitlab_issue event."
    )
    call_kwargs = mock_developer.create_mr_from_issue.call_args[1]
    assert call_kwargs.get("issue_iid") == 1, (
        f"Expected issue_iid=1 in create_mr_from_issue() call: {call_kwargs}"
    )

    # Verify audit log has the gitlab_issue event recorded
    rows = _query_audit(tmp_audit_db.db_path, "EVENT_GITLAB_ISSUE")
    assert len(rows) >= 1, "Expected EVENT_GITLAB_ISSUE record in audit log."
