"""
Fall Detection — TFLite Flatbuffer → C Header Generator
=========================================================
Converts models/fall_detector.tflite to a C byte-array header suitable
for inclusion in TFLite Micro firmware (STM32L4 / CMSIS-NN).

Output: firmware/fall_detection/fall_detector_model.h

The generated header:
  - Declares the model array as `const unsigned char g_fall_detector_model[]`
    with `__attribute__((aligned(8)))` for DMA alignment on Cortex-M
  - Includes model metadata as compile-time constants
  - Follows the TFLite Micro embedding convention

Usage:
    python generate_c_header.py \
        --tflite models/fall_detector.tflite \
        --output firmware/fall_detection/fall_detector_model.h

IEC 62304 Design Record: FD-FW-001 Rev 1.0
"""

from __future__ import annotations

import argparse
import datetime
import logging
import sys
from pathlib import Path

logger = logging.getLogger("fall_detector.gen_header")
logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s  %(levelname)-8s  %(message)s")


HEADER_TEMPLATE = """\
/**
 * @file    fall_detector_model.h
 * @brief   FallNet-Micro TFLite INT8 model — embedded flatbuffer
 *
 * Auto-generated by generate_c_header.py on {date}
 * Source: {source_path}
 * Model size: {size_bytes} bytes ({size_kb:.1f} KB)
 *
 * IEC 62304 Document: FD-FW-001 Rev 1.0
 * DO NOT EDIT — regenerate from the canonical .tflite file.
 *
 * Usage (TFLite Micro):
 *   #include "fall_detector_model.h"
 *   const tflite::Model* model = tflite::GetModel(g_fall_detector_model);
 *   // Verify model schema version before use:
 *   assert(model->version() == TFLITE_SCHEMA_VERSION);
 */

#ifndef FALL_DETECTOR_MODEL_H_
#define FALL_DETECTOR_MODEL_H_

#ifdef __cplusplus
extern "C" {{
#endif

/* ── Model metadata ─────────────────────────────────────────────────────── */
/** Total size of the flatbuffer in bytes */
#define FALL_DETECTOR_MODEL_SIZE     {size_bytes}UL

/** Input tensor shape: [1 x WINDOW_SAMPLES x CHANNELS] */
#define FALL_DETECTOR_WINDOW_SAMPLES 400U
#define FALL_DETECTOR_CHANNELS       6U

/**
 * Quantization parameters for the input tensor.
 * Input raw = (float_value / input_scale) + input_zero_point
 * These values are read from the flatbuffer at runtime; the macros
 * below are provided for documentation and static-analysis purposes.
 */
#define FALL_DETECTOR_INPUT_DTYPE    int8_t
#define FALL_DETECTOR_OUTPUT_DTYPE   int8_t

/**
 * Classification threshold (INT8 dequantised output ≥ this → fall detected).
 * Set conservatively to achieve sensitivity ≥ 0.95.
 * Validated per FD-VR-001 Rev 1.0.
 */
#define FALL_DETECTOR_THRESHOLD_F    {threshold:.2f}f

/* ── Model flatbuffer (aligned for DMA on Cortex-M) ────────────────────── */
/** @note: __attribute__((aligned(8))) required by TFLite Micro flatbuffer parser */
static const unsigned char g_fall_detector_model[] __attribute__((aligned(8))) = {{
{hex_array}
}};

/* Compile-time size check */
_Static_assert(
    sizeof(g_fall_detector_model) == FALL_DETECTOR_MODEL_SIZE,
    "g_fall_detector_model size mismatch — regenerate header from .tflite"
);

#ifdef __cplusplus
}}  /* extern "C" */
#endif

#endif  /* FALL_DETECTOR_MODEL_H_ */
"""


def tflite_to_c_array(data: bytes, bytes_per_line: int = 12) -> str:
    """Format raw bytes as a C hex literal array, 12 bytes per line."""
    lines = []
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i: i + bytes_per_line]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        trailing = "," if (i + bytes_per_line) < len(data) else ""
        lines.append(f"  {hex_vals}{trailing}")
    return "\n".join(lines)


def generate_header(
    tflite_path: Path,
    output_path: Path,
    threshold: float = 0.50,
) -> None:
    if not tflite_path.exists():
        raise FileNotFoundError(f"TFLite model not found: {tflite_path}")

    data = tflite_path.read_bytes()
    logger.info("Model size: %d bytes (%.1f KB)", len(data), len(data) / 1024)

    if len(data) > 100 * 1024:
        raise ValueError(
            f"Model size {len(data) / 1024:.1f} KB exceeds 100 KB STM32L4 budget")

    hex_array = tflite_to_c_array(data)
    header = HEADER_TEMPLATE.format(
        date=datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
        source_path=str(tflite_path),
        size_bytes=len(data),
        size_kb=len(data) / 1024,
        threshold=threshold,
        hex_array=hex_array,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header, encoding="utf-8")
    logger.info("C header written → %s (%d lines)", output_path,
                header.count("\n"))


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Convert TFLite model to C header")
    p.add_argument("--tflite",    type=Path,
                   default=Path("models/fall_detector.tflite"))
    p.add_argument("--output",    type=Path,
                   default=Path("firmware/fall_detection/fall_detector_model.h"))
    p.add_argument("--threshold", type=float, default=0.50,
                   help="Classification threshold embedded as macro")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    generate_header(args.tflite, args.output, args.threshold)
    logger.info("Done.")
